### ISSUE TITLE
RGBA instead of RGB

### ISSUE THREAD

**Issue by wojciech-niedzwiedz-napa** [techsoft3d/hoops-web-viewer#4]
Hi, 
is it possible to specify alpha channel for 
setNodesFaceColor?
The method itself uses RGB.

**Comment by girroir** [comment]
You can set opacity (alpha) through the setNodesOpacity() and setNodesOpacities() methods on the Model object:
https://docs.techsoft3d.com/communicator/latest/build/api_ref/typedoc/classes/communicator.model.html#setnodesopacity
https://docs.techsoft3d.com/communicator/latest/build/api_ref/typedoc/classes/communicator.model.html#setnodesopacities
