### ISSUE TITLE
Hoops installer hasn't update to new version 2023.0.0

### ISSUE THREAD

**Issue by ihryshchenko** [techsoft3d/hoops-web-viewer#5]
@girroir, @OragonEfreet, @techsoftrick 
I've noticed that trying to install (using HOOPS Installer) new version of HOOPS Communicator the version still 2022.2.1.
In Installation logs also old version
![image](https://user-images.githubusercontent.com/95427316/210792751-5121dba0-bf9e-4d1f-bd19-22978cd06fec.png)

**Comment by techsoftrick** [comment]
Hello, thank you very much for reaching out. The installer will not be updated for some time. Is there a reason that you need the 2023 release in particular? We may be able to get this version of the release to you in a different way.

**Comment by ihryshchenko** [comment]
Hello @techsoftrick. 
Thanks for fast feedback. 2023 release has features that are valuable for our project.
Where can I find **hoops_web_viewer_monolithic.js**?
It was in previous releases in HOOPS installer.

**Comment by techsoftrick** [comment]
Hello @ihryshchenko,

I have added you as a contributor to this private repo. There you will find the requested file. 

https://github.com/techsoftrick/hoops_monolithic_2023

Thank you so much for your interest.

**Comment by ihryshchenko** [comment]
Really great news! We appreciate your help! Thanks.
